---
- name: Deploy K3s
  hosts: K3s
  become: True
  gather_facts: yes   
  tasks:
    - name: Package containerd is installed
      apt:
        pkg: 
          - containerd
        update_cache: yes
    - name: Ensure K3s installer is present on system
      get_url:
        url: https://get.k3s.io
        dest: /home/{{ ansible_user }}/k3s
        force: yes
    - name: Ensure K3s installed
      shell: cat /home/{{ ansible_user }}/k3s | INSTALL_K3S_SKIP_ENABLE=true INSTALL_K3S_SKIP_START=true sh -
    - name: enable ip forwarding
      lineinfile:
        dest: /etc/ufw/sysctl.conf
        regexp: '^#{{ item }}$'
        line: "{{ item }}"
      with_items:
        - net/ipv4/ip_forward=1
        - net/ipv6/conf/default/forwarding=1
        - net/ipv6/conf/all/forwarding=1
    - name: enable forwarding in ufw
      lineinfile:
        dest: /etc/default/ufw
        regexp: '^DEFAULT_FORWARD_POLICY=.*$'
        line: DEFAULT_FORWARD_POLICY="ACCEPT"
    - name: Ensure inbound rules for K3s master node are enabled
      ufw:
        rule: allow
        proto: tcp
        src: "{{ item }}"
        to_port: "6443"
      with_items:
        - "192.168.4.0/24" 
        - "10.42.0.0/16"
    - name: Ensure inbound rules for K3s master node are enabled
      ufw:
        rule: allow
        proto: tcp
        src: 192.168.4.0/24
        to_port: "{{ item }}"
      with_items:
        - "10250"
    - name: Ensure inbound rules for K3s worker node
      ufw:
        rule: allow
        proto: udp
        src: 192.168.4.0/24
        to_port: "{{ item }}"
      with_items:
        - "8472"
    - name: Ensure inbound rules for K3s worker node
      ufw:
        rule: allow
        direction: in
        interface: cni0
    - name: Ensure outbound rules for K3s worker node
      ufw:
        rule: allow
        direction: out
        interface: cni0
    - name: Restarted ufw
      systemd:
        state: restarted
        daemon_reload: yes
        name: ufw