---
- name: Profiling k3s
  hosts: K3s
  become: False
  gather_facts: True
  vars: 
    platform: "K3s"
    K3S_VERSION: v1.20.0+k3s2
    SIMULATION_WAIT_INTERVAL: "30"
    SIMULATION_IDLE_INTERVAL: "300"
    SIMULATION_END_INTERVAL: "1000"
  tasks: 
    - include_tasks: profiling-k3s.yaml
      with_sequence: start=3061 end=3081 stride=1
      loop_control:
        loop_var: simulation
      tags: 
       - simulation
       - platform
       - prepare
       - teardown